//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khadamat_CustomerApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Khadamat_CustomerApp.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string about_AboutUsTitle {
            get {
                return ResourceManager.GetString("about_AboutUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo.
        /// </summary>
        internal static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        internal static string ago {
            get {
                return ResourceManager.GetString("ago", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attachment size must be less than 1 MB.
        /// </summary>
        internal static string msg_attachmentError
        {
            get {
                return ResourceManager.GetString("msg_attachmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        internal static string changelang_Arabic {
            get {
                return ResourceManager.GetString("changelang_Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string changelang_English {
            get {
                return ResourceManager.GetString("changelang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        internal static string changelang_PickerPlaceholder {
            get {
                return ResourceManager.GetString("changelang_PickerPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string chat_DeleteChat {
            get {
                return ResourceManager.GetString("chat_DeleteChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string chat_HeaderTitle {
            get {
                return ResourceManager.GetString("chat_HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a Message.
        /// </summary>
        internal static string chatdetail_EnterMsgPlaceHolder {
            get {
                return ResourceManager.GetString("chatdetail_EnterMsgPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND.
        /// </summary>
        internal static string contact_ContactUsBtn {
            get {
                return ResourceManager.GetString("contact_ContactUsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string contact_ContactUsEmailTitle {
            get {
                return ResourceManager.GetString("contact_ContactUsEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        internal static string contact_ContactUsEmailValue {
            get {
                return ResourceManager.GetString("contact_ContactUsEmailValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string contact_ContactUsNameTitle {
            get {
                return ResourceManager.GetString("contact_ContactUsNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        internal static string contact_ContactUsNameValue {
            get {
                return ResourceManager.GetString("contact_ContactUsNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string contact_ContactUsServiceTitle {
            get {
                return ResourceManager.GetString("contact_ContactUsServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your message here.
        /// </summary>
        internal static string contact_ContactUsServiceValue {
            get {
                return ResourceManager.GetString("contact_ContactUsServiceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string contact_ContactUsTitle {
            get {
                return ResourceManager.GetString("contact_ContactUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Service.
        /// </summary>
        internal static string coordinator_Name {
            get {
                return ResourceManager.GetString("coordinator_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LET&apos;S START.
        /// </summary>
        internal static string cyp_Button {
            get {
                return ResourceManager.GetString("cyp_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country *.
        /// </summary>
        internal static string cyp_Country {
            get {
                return ResourceManager.GetString("cyp_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Country.
        /// </summary>
        internal static string cyp_CountryPlaceholder {
            get {
                return ResourceManager.GetString("cyp_CountryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Job.
        /// </summary>
        internal static string cyp_CurrentJob {
            get {
                return ResourceManager.GetString("cyp_CurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current job.
        /// </summary>
        internal static string cyp_CurrentJobPlaceholder {
            get {
                return ResourceManager.GetString("cyp_CurrentJobPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth *.
        /// </summary>
        internal static string cyp_DOB {
            get {
                return ResourceManager.GetString("cyp_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your Date of Birth.
        /// </summary>
        internal static string cyp_DOBPlaceholder {
            get {
                return ResourceManager.GetString("cyp_DOBPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string cyp_Email {
            get {
                return ResourceManager.GetString("cyp_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        internal static string cyp_EmailPlaceholder {
            get {
                return ResourceManager.GetString("cyp_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Your Profile.
        /// </summary>
        internal static string cyp_HeaderTitle {
            get {
                return ResourceManager.GetString("cyp_HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Location *.
        /// </summary>
        internal static string cyp_Location {
            get {
                return ResourceManager.GetString("cyp_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Location successfully taken..
        /// </summary>
        internal static string cyp_LocationPickupAlert {
            get {
                return ResourceManager.GetString("cyp_LocationPickupAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write description of your location here....
        /// </summary>
        internal static string cyp_LocationPlaceholder {
            get {
                return ResourceManager.GetString("cyp_LocationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        internal static string cyp_MaritalStatus {
            get {
                return ResourceManager.GetString("cyp_MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your marital status.
        /// </summary>
        internal static string cyp_MaritalStatusPlaceholder {
            get {
                return ResourceManager.GetString("cyp_MaritalStatusPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name *.
        /// </summary>
        internal static string cyp_Name {
            get {
                return ResourceManager.GetString("cyp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        internal static string cyp_NamePlaceholder {
            get {
                return ResourceManager.GetString("cyp_NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province *.
        /// </summary>
        internal static string cyp_Province {
            get {
                return ResourceManager.GetString("cyp_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Provience.
        /// </summary>
        internal static string cyp_ProvincePlaceholder {
            get {
                return ResourceManager.GetString("cyp_ProvincePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fields with the * symbol are required..
        /// </summary>
        internal static string cyp_RequiredField {
            get {
                return ResourceManager.GetString("cyp_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street .
        /// </summary>
        internal static string cyp_Street {
            get {
                return ResourceManager.GetString("cyp_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap here to get your current location..
        /// </summary>
        internal static string cyp_StreetPlaceholder {
            get {
                return ResourceManager.GetString("cyp_StreetPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read &amp; agree with Term &amp; Conditions.
        /// </summary>
        internal static string cyp_TermConditionBlack {
            get {
                return ResourceManager.GetString("cyp_TermConditionBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Chat.
        /// </summary>
        internal static string DeleteChat {
            get {
                return ResourceManager.GetString("DeleteChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete chat?.
        /// </summary>
        internal static string DeleteChatConfirm {
            get {
                return ResourceManager.GetString("DeleteChatConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Group.
        /// </summary>
        internal static string DeleteGroup {
            get {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this group?.
        /// </summary>
        internal static string DeleteGroupConfirm {
            get {
                return ResourceManager.GetString("DeleteGroupConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string editprofile_EditProfileSaveBtn {
            get {
                return ResourceManager.GetString("editprofile_EditProfileSaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string editprofile_EditProfileTitle {
            get {
                return ResourceManager.GetString("editprofile_EditProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be blank..
        /// </summary>
        internal static string err_BlankPassword {
            get {
                return ResourceManager.GetString("err_BlankPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password didn&apos;t match..
        /// </summary>
        internal static string err_ConfirmPassword {
            get {
                return ResourceManager.GetString("err_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location permission is denied for the app. Do you want to give permission?.
        /// </summary>
        internal static string error_AppLocationPermissionDisable {
            get {
                return ResourceManager.GetString("error_AppLocationPermissionDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name, email and description..
        /// </summary>
        internal static string error_BlankAllField {
            get {
                return ResourceManager.GetString("error_BlankAllField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email.
        /// </summary>
        internal static string error_Blankemail {
            get {
                return ResourceManager.GetString("error_Blankemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter OTP..
        /// </summary>
        internal static string error_BlankOtp {
            get {
                return ResourceManager.GetString("error_BlankOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter phone number..
        /// </summary>
        internal static string error_BlankPhone {
            get {
                return ResourceManager.GetString("error_BlankPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Phone Number and password..
        /// </summary>
        internal static string error_BlankPhonePassword {
            get {
                return ResourceManager.GetString("error_BlankPhonePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill all the required fields..
        /// </summary>
        internal static string error_BlankRequiredField {
            get {
                return ResourceManager.GetString("error_BlankRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write description..
        /// </summary>
        internal static string error_ContactUsDescription {
            get {
                return ResourceManager.GetString("error_ContactUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email id..
        /// </summary>
        internal static string error_ContactUsEmail {
            get {
                return ResourceManager.GetString("error_ContactUsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name..
        /// </summary>
        internal static string error_ContactUsName {
            get {
                return ResourceManager.GetString("error_ContactUsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Device GPS location is disabled. Do you want to enable location service?.
        /// </summary>
        internal static string error_DeviceLocationDisable {
            get {
                return ResourceManager.GetString("error_DeviceLocationDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your date of birth must not be greater than current date..
        /// </summary>
        internal static string error_DOBError {
            get {
                return ResourceManager.GetString("error_DOBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email..
        /// </summary>
        internal static string error_EmailValidation {
            get {
                return ResourceManager.GetString("error_EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occuring while sending file.
        /// </summary>
        internal static string error_FileUploading {
            get {
                return ResourceManager.GetString("error_FileUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occuring while sending Image.
        /// </summary>
        internal static string error_ImageUploading {
            get {
                return ResourceManager.GetString("error_ImageUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your Internet Connection.
        /// </summary>
        internal static string error_InternetError {
            get {
                return ResourceManager.GetString("error_InternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Extension is invalid.
        /// </summary>
        internal static string error_invalidFileExtension {
            get {
                return ResourceManager.GetString("error_invalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Date &amp; Time must be greater than Current Date &amp; Time..
        /// </summary>
        internal static string error_jobdatetime {
            get {
                return ResourceManager.GetString("error_jobdatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter description of your service..
        /// </summary>
        internal static string error_JobRequestServiceDescriptionBlank {
            get {
                return ResourceManager.GetString("error_JobRequestServiceDescriptionBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter venue name..
        /// </summary>
        internal static string error_JobRequestVenueBlank {
            get {
                return ResourceManager.GetString("error_JobRequestVenueBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate the worker job..
        /// </summary>
        internal static string error_ReviewError {
            get {
                return ResourceManager.GetString("error_ReviewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some issue while connecting to server. Please check your internet connection or try again after some time..
        /// </summary>
        internal static string error_ServerError {
            get {
                return ResourceManager.GetString("error_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept terms and conditions..
        /// </summary>
        internal static string error_TermCondition {
            get {
                return ResourceManager.GetString("error_TermCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your age must be 18 or above.
        /// </summary>
        internal static string error_underAge {
            get {
                return ResourceManager.GetString("error_underAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid phone number.
        /// </summary>
        internal static string error_ValidPhone {
            get {
                return ResourceManager.GetString("error_ValidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string faq {
            get {
                return ResourceManager.GetString("faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance Officer.
        /// </summary>
        internal static string finance_officername {
            get {
                return ResourceManager.GetString("finance_officername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Phone Number associated with your account..
        /// </summary>
        internal static string forgot_PasswordMsg {
            get {
                return ResourceManager.GetString("forgot_PasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORGOT YOUR PASSWORD.
        /// </summary>
        internal static string forgot_PasswordTitle {
            get {
                return ResourceManager.GetString("forgot_PasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Conditioner.
        /// </summary>
        internal static string home_ACRepair {
            get {
                return ResourceManager.GetString("home_ACRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Appliance Repairs.
        /// </summary>
        internal static string home_AppliancesRepair {
            get {
                return ResourceManager.GetString("home_AppliancesRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Cleaning.
        /// </summary>
        internal static string home_CleaningService {
            get {
                return ResourceManager.GetString("home_CleaningService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrician.
        /// </summary>
        internal static string home_ElectricianService {
            get {
                return ResourceManager.GetString("home_ElectricianService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laptop Repair.
        /// </summary>
        internal static string home_LaptopRepair {
            get {
                return ResourceManager.GetString("home_LaptopRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Maintenance.
        /// </summary>
        internal static string home_Maintenance {
            get {
                return ResourceManager.GetString("home_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string home_PageTitle {
            get {
                return ResourceManager.GetString("home_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painter.
        /// </summary>
        internal static string home_PainterService {
            get {
                return ResourceManager.GetString("home_PainterService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plumbing.
        /// </summary>
        internal static string home_PlumbingService {
            get {
                return ResourceManager.GetString("home_PlumbingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Service.
        /// </summary>
        internal static string home_searchPlaceHolder {
            get {
                return ResourceManager.GetString("home_searchPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Your Service.
        /// </summary>
        internal static string home_searchTitle {
            get {
                return ResourceManager.GetString("home_searchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem Ipsum is Simply dummy text of the printing.
        /// </summary>
        internal static string home_searchTitle2 {
            get {
                return ResourceManager.GetString("home_searchTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Detail.
        /// </summary>
        internal static string jobDetail_Title {
            get {
                return ResourceManager.GetString("jobDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category *.
        /// </summary>
        internal static string jobrequest_CategoryTitle {
            get {
                return ResourceManager.GetString("jobrequest_CategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time *.
        /// </summary>
        internal static string jobrequest_DateTimeTitle {
            get {
                return ResourceManager.GetString("jobrequest_DateTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write job description here....
        /// </summary>
        internal static string jobrequest_DescriptionPlaceHolder {
            get {
                return ResourceManager.GetString("jobrequest_DescriptionPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request.
        /// </summary>
        internal static string jobrequest_HeaderTitle {
            get {
                return ResourceManager.GetString("jobrequest_HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Cancel Reason.
        /// </summary>
        internal static string jobrequest_JobCloseReason {
            get {
                return ResourceManager.GetString("jobrequest_JobCloseReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string jobrequest_Location {
            get {
                return ResourceManager.GetString("jobrequest_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string jobrequest_PopupBtn {
            get {
                return ResourceManager.GetString("jobrequest_PopupBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your service request have been submitted. We will get back you soon..
        /// </summary>
        internal static string jobrequest_PopupMsg {
            get {
                return ResourceManager.GetString("jobrequest_PopupMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Description.
        /// </summary>
        internal static string jobrequest_QuoteDescriptionTitle {
            get {
                return ResourceManager.GetString("jobrequest_QuoteDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string jobrequest_QuoteTitle {
            get {
                return ResourceManager.GetString("jobrequest_QuoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Service *.
        /// </summary>
        internal static string jobrequest_ServiceDescription {
            get {
                return ResourceManager.GetString("jobrequest_ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Service *.
        /// </summary>
        internal static string jobrequest_ServiceTypeTitle {
            get {
                return ResourceManager.GetString("jobrequest_ServiceTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT REQUEST.
        /// </summary>
        internal static string jobrequest_SubmitBtn {
            get {
                return ResourceManager.GetString("jobrequest_SubmitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter job venue....
        /// </summary>
        internal static string jobrequest_VenuePlaceHolder {
            get {
                return ResourceManager.GetString("jobrequest_VenuePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue *.
        /// </summary>
        internal static string jobrequest_VenueTitle {
            get {
                return ResourceManager.GetString("jobrequest_VenueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string login_ForgotPswd {
            get {
                return ResourceManager.GetString("login_ForgotPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string login_Password {
            get {
                return ResourceManager.GetString("login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string login_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("login_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string login_PhoneNumber {
            get {
                return ResourceManager.GetString("login_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number.
        /// </summary>
        internal static string login_PhoneNumberPlaceholder {
            get {
                return ResourceManager.GetString("login_PhoneNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User ! .
        /// </summary>
        internal static string login_Signup1 {
            get {
                return ResourceManager.GetString("login_Signup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string login_Signup2 {
            get {
                return ResourceManager.GetString("login_Signup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string login_Title {
            get {
                return ResourceManager.GetString("login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Phone Number &amp; Password.
        /// </summary>
        internal static string login_TitleMsg {
            get {
                return ResourceManager.GetString("login_TitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        internal static string LogoutMsg {
            get {
                return ResourceManager.GetString("LogoutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Location.
        /// </summary>
        internal static string map_headerTitle {
            get {
                return ResourceManager.GetString("map_headerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engaged.
        /// </summary>
        internal static string marital_Engaged {
            get {
                return ResourceManager.GetString("marital_Engaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its Complicated.
        /// </summary>
        internal static string marital_ItsComplicated {
            get {
                return ResourceManager.GetString("marital_ItsComplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        internal static string marital_Married {
            get {
                return ResourceManager.GetString("marital_Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In An OpenRelationship.
        /// </summary>
        internal static string marital_OpenRelation {
            get {
                return ResourceManager.GetString("marital_OpenRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In A Relationship.
        /// </summary>
        internal static string marital_relation {
            get {
                return ResourceManager.GetString("marital_relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string marital_Single {
            get {
                return ResourceManager.GetString("marital_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widowed.
        /// </summary>
        internal static string marital_Widowed {
            get {
                return ResourceManager.GetString("marital_Widowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string menu_AboutUs {
            get {
                return ResourceManager.GetString("menu_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats.
        /// </summary>
        internal static string menu_Chats {
            get {
                return ResourceManager.GetString("menu_Chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string menu_ContactUs {
            get {
                return ResourceManager.GetString("menu_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string menu_Home {
            get {
                return ResourceManager.GetString("menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string menu_LogOut {
            get {
                return ResourceManager.GetString("menu_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Booking.
        /// </summary>
        internal static string menu_MyBooking {
            get {
                return ResourceManager.GetString("menu_MyBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string menu_PrivacyPolicy {
            get {
                return ResourceManager.GetString("menu_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string menu_Profile {
            get {
                return ResourceManager.GetString("menu_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string menu_TermCondition {
            get {
                return ResourceManager.GetString("menu_TermCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        internal static string menu_ViewProfile {
            get {
                return ResourceManager.GetString("menu_ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        internal static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string months {
            get {
                return ResourceManager.GetString("months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string msg_Today {
            get {
                return ResourceManager.GetString("msg_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string msg_Yesterday {
            get {
                return ResourceManager.GetString("msg_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Again.
        /// </summary>
        internal static string mybooking_BookAgain {
            get {
                return ResourceManager.GetString("mybooking_BookAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string mybooking_Cancel {
            get {
                return ResourceManager.GetString("mybooking_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string mybooking_Cancelled {
            get {
                return ResourceManager.GetString("mybooking_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string mybooking_Chat {
            get {
                return ResourceManager.GetString("mybooking_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Review.
        /// </summary>
        internal static string mybooking_CheckReview {
            get {
                return ResourceManager.GetString("mybooking_CheckReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string mybooking_Completed {
            get {
                return ResourceManager.GetString("mybooking_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator.
        /// </summary>
        internal static string mybooking_Coordinator {
            get {
                return ResourceManager.GetString("mybooking_Coordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give Review.
        /// </summary>
        internal static string mybooking_GiveReview {
            get {
                return ResourceManager.GetString("mybooking_GiveReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Bookings.
        /// </summary>
        internal static string mybooking_HeaderTitle {
            get {
                return ResourceManager.GetString("mybooking_HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Progress.
        /// </summary>
        internal static string mybooking_InProgress {
            get {
                return ResourceManager.GetString("mybooking_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, you don&apos;t have any booking.
        /// </summary>
        internal static string mybooking_NoBookingFound {
            get {
                return ResourceManager.GetString("mybooking_NoBookingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string mybooking_Pending {
            get {
                return ResourceManager.GetString("mybooking_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Present.
        /// </summary>
        internal static string NoDataPresent {
            get {
                return ResourceManager.GetString("NoDataPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Lost.
        /// </summary>
        internal static string noInternet_msg1 {
            get {
                return ResourceManager.GetString("noInternet_msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection..
        /// </summary>
        internal static string noInternet_msg2 {
            get {
                return ResourceManager.GetString("noInternet_msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string noInternet_TryAgainBtn {
            get {
                return ResourceManager.GetString("noInternet_TryAgainBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string notification_Accept {
            get {
                return ResourceManager.GetString("notification_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 days ago.
        /// </summary>
        internal static string notification_date {
            get {
                return ResourceManager.GetString("notification_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string notification_PageTitle {
            get {
                return ResourceManager.GetString("notification_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string notification_Reject {
            get {
                return ResourceManager.GetString("notification_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nate Parker has completed your job request..
        /// </summary>
        internal static string notification_title {
            get {
                return ResourceManager.GetString("notification_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        internal static string notification_ViewDetail {
            get {
                return ResourceManager.GetString("notification_ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Invoice.
        /// </summary>
        internal static string notification_ViewInvoice {
            get {
                return ResourceManager.GetString("notification_ViewInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded OTP request max attempt , please call to the customer service number in order to get your OTP..
        /// </summary>
        internal static string otp_Callme {
            get {
                return ResourceManager.GetString("otp_Callme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent verification code on your registered Email..
        /// </summary>
        internal static string otp_EmailVerificationCodeMsg {
            get {
                return ResourceManager.GetString("otp_EmailVerificationCodeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER OTP.
        /// </summary>
        internal static string otp_EnterOtpTitle {
            get {
                return ResourceManager.GetString("otp_EnterOtpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend OTP.
        /// </summary>
        internal static string otp_Resend {
            get {
                return ResourceManager.GetString("otp_Resend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Support Call.
        /// </summary>
        internal static string otp_SupportCall
        {
            get {
                return ResourceManager.GetString("otp_SupportCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent verification code on your Mobile.
        /// </summary>
        internal static string otp_VerificationCodeMsg {
            get {
                return ResourceManager.GetString("otp_VerificationCodeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string privacy_PrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("privacy_PrivacyPolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country .
        /// </summary>
        internal static string profile_Country {
            get {
                return ResourceManager.GetString("profile_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Job.
        /// </summary>
        internal static string profile_CurrentJob {
            get {
                return ResourceManager.GetString("profile_CurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string profile_DOB {
            get {
                return ResourceManager.GetString("profile_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string profile_Email {
            get {
                return ResourceManager.GetString("profile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Location.
        /// </summary>
        internal static string profile_Location {
            get {
                return ResourceManager.GetString("profile_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        internal static string profile_MaritalStatus {
            get {
                return ResourceManager.GetString("profile_MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string profile_Name {
            get {
                return ResourceManager.GetString("profile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Email ID.
        /// </summary>
        internal static string profile_PopupEmailTitle {
            get {
                return ResourceManager.GetString("profile_PopupEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Phone Number.
        /// </summary>
        internal static string profile_PopupPhoneTitle {
            get {
                return ResourceManager.GetString("profile_PopupPhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string profile_ProfileTitle {
            get {
                return ResourceManager.GetString("profile_ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string profile_Province {
            get {
                return ResourceManager.GetString("profile_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string profile_Street {
            get {
                return ResourceManager.GetString("profile_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE YOUR PASSWORD.
        /// </summary>
        internal static string pswd_ChangePswdTitle {
            get {
                return ResourceManager.GetString("pswd_ChangePswdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your password to login.
        /// </summary>
        internal static string pswd_ChoosePswdLogin {
            get {
                return ResourceManager.GetString("pswd_ChoosePswdLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string pswd_ConfirmPassword {
            get {
                return ResourceManager.GetString("pswd_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string pswd_ConfirmPswdPlaceholder {
            get {
                return ResourceManager.GetString("pswd_ConfirmPswdPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE YOUR PASSWORD.
        /// </summary>
        internal static string pswd_CreatePswdTitle {
            get {
                return ResourceManager.GetString("pswd_CreatePswdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        internal static string pswd_EnterPswdPlaceholder {
            get {
                return ResourceManager.GetString("pswd_EnterPswdPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string pswd_NewPassword {
            get {
                return ResourceManager.GetString("pswd_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your new password.
        /// </summary>
        internal static string pswd_NewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("pswd_NewPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string pswd_OldPassword {
            get {
                return ResourceManager.GetString("pswd_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your old password.
        /// </summary>
        internal static string pswd_OldPasswordPlaceholder {
            get {
                return ResourceManager.GetString("pswd_OldPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER YOUR PHONE.
        /// </summary>
        internal static string reg_EnterPhoneNumberTitle {
            get {
                return ResourceManager.GetString("reg_EnterPhoneNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number.
        /// </summary>
        internal static string reg_PhoneNumber {
            get {
                return ResourceManager.GetString("reg_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT.
        /// </summary>
        internal static string reg_SubmitBtn {
            get {
                return ResourceManager.GetString("reg_SubmitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll send verification code on your mobile.
        /// </summary>
        internal static string reg_VerificationCodeMsg {
            get {
                return ResourceManager.GetString("reg_VerificationCodeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write here....
        /// </summary>
        internal static string review_CommentPlaceHolder {
            get {
                return ResourceManager.GetString("review_CommentPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRITE SOMETHING.
        /// </summary>
        internal static string review_CommentTitle {
            get {
                return ResourceManager.GetString("review_CommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Comment.
        /// </summary>
        internal static string review_CommentTitle1 {
            get {
                return ResourceManager.GetString("review_CommentTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        internal static string review_DoneBtn {
            get {
                return ResourceManager.GetString("review_DoneBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW WOULD YOU RATE?.
        /// </summary>
        internal static string review_RatingTitle {
            get {
                return ResourceManager.GetString("review_RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rating.
        /// </summary>
        internal static string review_RatingTitle1 {
            get {
                return ResourceManager.GetString("review_RatingTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give Review.
        /// </summary>
        internal static string review_ReviewTitle {
            get {
                return ResourceManager.GetString("review_ReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Your Review.
        /// </summary>
        internal static string review_ReviewTitle1 {
            get {
                return ResourceManager.GetString("review_ReviewTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string setting_ChangeLanguage {
            get {
                return ResourceManager.GetString("setting_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string setting_ChangePassword {
            get {
                return ResourceManager.GetString("setting_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string setting_ContactUs {
            get {
                return ResourceManager.GetString("setting_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string setting_HeaderTitle {
            get {
                return ResourceManager.GetString("setting_HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate This App.
        /// </summary>
        internal static string setting_RateApp {
            get {
                return ResourceManager.GetString("setting_RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string spjob_PopTitle {
            get {
                return ResourceManager.GetString("spjob_PopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write the your comments why you want to cancel this job.
        /// </summary>
        internal static string spjob_popupErrorMsg {
            get {
                return ResourceManager.GetString("spjob_popupErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to cancel this request..
        /// </summary>
        internal static string spjob_PopupMsg {
            get {
                return ResourceManager.GetString("spjob_PopupMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please let us know why you want to cancel this job request?.
        /// </summary>
        internal static string spjob_PopupMsg1 {
            get {
                return ResourceManager.GetString("spjob_PopupMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add your comments.
        /// </summary>
        internal static string spjob_PopupPlaceholder {
            get {
                return ResourceManager.GetString("spjob_PopupPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap, Wash Basin and Sink.
        /// </summary>
        internal static string subservice_serviceName1 {
            get {
                return ResourceManager.GetString("subservice_serviceName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks and Leakages.
        /// </summary>
        internal static string subservice_serviceName2 {
            get {
                return ResourceManager.GetString("subservice_serviceName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toilet and Sanitary Work.
        /// </summary>
        internal static string subservice_serviceName3 {
            get {
                return ResourceManager.GetString("subservice_serviceName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending file Successfully.
        /// </summary>
        internal static string success_FileUploading {
            get {
                return ResourceManager.GetString("success_FileUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Image Successfully.
        /// </summary>
        internal static string success_ImageUploading {
            get {
                return ResourceManager.GetString("success_ImageUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string support_HeaderTitle {
            get {
                return ResourceManager.GetString("support_HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string term_Title {
            get {
                return ResourceManager.GetString("term_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Detail.
        /// </summary>
        internal static string webview_InvoiceHeader {
            get {
                return ResourceManager.GetString("webview_InvoiceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        internal static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
